### ISSUE TITLE
Switch default shell on Windows to PowerShell

### ISSUE THREAD

**Issue by arctic-hen7** [arctic-hen7/bonnie#15]
It's been proposed in #12 that the default shell on Windows should be switched to PowerShell. Since that issue contains another main point, I'm moving the conversation on the matter of changing the default to here.

**Comment by arctic-hen7** [comment]
Implementing this, while trivial, is not something I'm entirely yet convinced to be the correct course of action. I personally use Linux, so if a Windows user could explain to me why this change should be made (@ostev?), that would be fantastic!

**Comment by ostev** [comment]
Commands like `ls` **don't exist in `cmd`**. It will just error out. This causes some potential incompatibility with scripts designed to work on `sh`. PowerShell is more compatible with other shells.

**Comment by arctic-hen7** [comment]
But in the context of the new changes which allow the user to specify the default shell on Windows to be PowerShell just by adding this to the top of their file, is a global change needed?

```toml
default_shell.targets.windows = ["powershell", "-c", "{COMMAND}"]
```

**Comment by ostev** [comment]
Having sensible defaults would be the main reason – `cmd` is _really_ old at this point. Ultimately, the user could just set it to PowerShell themselves, but the tool could just save you the trouble.

It also makes makes Bonnie on Windows more compatible with Bonnie on Linux and macOS, without any configuration changes.

**Comment by arctic-hen7** [comment]
Okay. I guess my only remaining question then is what is the default on Windows if you open a command prompt? What would you normally use to execute a package installation for example?

**Comment by ostev** [comment]
That has a surprisingly complicated answer.

* PowerShell 7 (`pwsh`) is heavily encouraged by Microsoft, but is not included by default
* Windows PowerShell (`powershell`) opens when you open the "PowerShell" application
* `cmd` opens when you open the "Command Prompt" application, but is discouraged by Microsoft (with good reason)

I normally use PowerShell 7, but I had to manually install it. I also use the Windows Terminal application, which is also not included with the OS. Windows PowerShell now prompts you to install PowerShell 7 on startup.

**Comment by arctic-hen7** [comment]
Okay, so we'd be changing the default to Windows PowerShell then (thanks for the clarification), which is installed by default and typically used for tasks like package installation etc.?

**Comment by ostev** [comment]
Yes. I'd hazard a guess that a lot of people use PowerShell 7, but only `cmd` and Windows PowerShell are guaranteed on Windows 7–10.

**Comment by arctic-hen7** [comment]
Okay. You've convinced me! Windows PowerShell will be the default shell on Windows from Bonnie v0.3.0 and above!

**Comment by arctic-hen7** [comment]
For those looking at this in future wondering how to use `cmd`, add this to the top of your `bonnie.toml`:

```toml
default_shell.generic = ["sh", "-c", "{COMMAND}"]
default_shell.targets.windows = ["cmd", "/C", "{COMMAND}"]
```

This sets the generic default shell to `sh` and to `cmd` on Windows. You can see more information in the [documentation](https://github.com/arctic-hen7/bonnie/wiki).
