### ISSUE TITLE
Global template support

### ISSUE THREAD

**Issue by arctic-hen7** [arctic-hen7/bonnie#16]
**Description**
Support for a global template in `~/.bonnie/template.toml` that would automatically be used instead of the pre-programmed default if it's present when `bonnie -i` is executed.

**Reasoning**
Bonnie currently lacks any form of global configuration ability. This is the best solution that provides both global configuration and atomicity and portability.

**Are you willing to work on an implementation of this?**
I'm happy to, but I think @ostev wanted to.

**Comment by arctic-hen7** [comment]
For reference, this was originally proposed in #12.

**Comment by ostev** [comment]
I'm currently working on a PR. I'm no Rustacean, so it will take me a little while.

One question: do you prefer `~/bonnie.toml` or `~/.bonnie/template.toml`?

**Comment by ostev** [comment]
Also: perhaps a merging of global with local configs would be interesting?

**Comment by arctic-hen7** [comment]
Great! No problem, let me know on Gitter if I there's anything you need. I think `~/.bonnie/template.toml` would make more sense.

**Comment by arctic-hen7** [comment]
> Also: perhaps a merging of global with local configs would be interesting at runtime? That way you could use your own shell on open-source projects that do not use your shell.

I'm not so much in favor of this at the moment. Bonnie needs to be portable, and everyone should get the same, predictable results at runtime. Each configuration file should be entirely self-contained.
