### ISSUE TITLE
Update to install node js packages

### ISSUE THREAD

**Issue by Valentine-Mario** [arctic-hen7/bonnie#3]
For this tool to compete among other current package managers, it should be able to install npm packages, dev dependencies, etc.

## Example
In your bonnie.toml file, users can specify dependencies as such

```
[dependecies]
express="1.0.1"
body-parser="2.0.1"

[dev-dependencies]
@node-types="1.0.1"
```

**Comment by arctic-hen7** [comment]
Hmm. My original aim with Bonnie was for it to be a general script manager, rather than tightly tied into one ecosystem or another. That being said, I'm not at all opposed to a universal package management system being implemented. I'll think on this further and draft out something.

**Comment by arctic-hen7** [comment]
Could you please elaborate on how you see package management working with Bonnie? With NodeJS, we'd be I assume running `npm` or `yarn`, which would require the use of `package.json` anyway...

**Comment by Valentine-Mario** [comment]
https://stackoverflow.com/questions/15035786/download-source-from-npm-without-installing-it

This answer on stackoverflow.com seems to be very helpful. But instead of wget, we could use reqwest for OS compatibility

**Comment by Valentine-Mario** [comment]
@arctic-hen7  For example, we GET the tarball URL by making a GET request to https://registry.npmjs.org/<package-name>/<version number> this would return a JSON which would contain dist which holds the URL to the zip folder which we now download to the node modules. This would have to be run recursively for every dependency in the package's package.json file.

**Comment by arctic-hen7** [comment]
I've generally used Yarn with NodeJS before, and I've found its package management systems to be fantastic, and complex. I feel it would be better to use such an existing tool rather than reimplement a huge amount of work.

**Comment by arctic-hen7** [comment]
@Valentine-Mario what are your thoughts on that idea?

**Comment by Valentine-Mario** [comment]
@arctic-hen7 I've started writing a draft implementation. Would push a draft PR soon.

I feel it would be a good feature to have and we can always improve on it.

**Comment by arctic-hen7** [comment]
Okay cool!

**Comment by arctic-hen7** [comment]
Alright given this issue specifically relates to NodeJS packages and the building of a dedicated package manager, I'm closing it. In future, if we decide to support wrapping *existing* package managers (with dedicated optimization teams etc.), a new issue can be opened.
